services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - book_club_postgres_data:/var/lib/postgresql/data

volumes:
  book_club_postgres_data:
